// _NKDBarcodePreferences_EOArchive.java
// Generated by EnterpriseObjects palette at Wednesday, April 23, 2003 21:08:53 America/New_York

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _NKDBarcodePreferences_EOArchive extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1;
    javax.swing.JPanel _nsView0;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1;

    public _NKDBarcodePreferences_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();


        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "metric")) != null)) {
            _jRadioButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton1");
        } else {
            _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Metric System"), "NSButtonCell1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "inches")) != null)) {
            _jRadioButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JRadioButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_jRadioButton0");
        } else {
            _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Inches & Mils"), "NSButtonCell");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "matrix")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 4, 2), "NSMatrix1");
        }

        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "matrix");
        }

        _jRadioButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "buttonCellClick", _jRadioButton1), ""));

        if (_replacedObjects.objectForKey("_jRadioButton1") == null) {
            _connect(_owner(), _jRadioButton1, "metric");
        }

        if (_replacedObjects.objectForKey("_jRadioButton0") == null) {
            _connect(_owner(), _jRadioButton0, "inches");
        }

        _jRadioButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "buttonCellClick", _jRadioButton0), ""));
    }

    protected void _init() {
        super._init();

        if (_replacedObjects.objectForKey("_jRadioButton1") == null) {
            _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_jRadioButton0") == null) {
            _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jRadioButton0.setSize(110, 18);
            _jRadioButton0.setLocation(0, 0);
            _nsMatrix0.add(_jRadioButton0);
            _jRadioButton1.setSize(110, 18);
            _jRadioButton1.setLocation(0, 20);
            _nsMatrix0.add(_jRadioButton1);
            _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsMatrix0.setSize(110, 38);
        _nsMatrix0.setLocation(21, 12);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsMatrix0);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(169, 62);
        _nsBox1.setLocation(2, 18);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Measurements", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(173, 82);
        _nsBox0.setLocation(13, 1);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsView0.setSize(199, 97);
        _eoFrame0.setTitle("Preferences");
        _eoFrame0.setLocation(303, 473);
        _eoFrame0.setSize(199, 97);
    }
}
